theme: jekyll-theme-cayman
title: <center><a href="#bottom"><img src:"https://media.discordapp.net/attachments/806343355264401478/844297128007303198/Image.png?width=125&height=110" alt="GAS BRAKE GO"></a></center>
description: <center> <a href="#top"><img src="https://cdn.discordapp.com/attachments/806343355264401478/837569890357346334/image0.png" alt="blog"></a></center>
google_analytics: G-SFJ80L12D6
linezero: <a href="#top"><img src="https://media.discordapp.net/attachments/806343355264401478/844297128007303198/Image.png?width=125&height=110" alt="blog"></a>
lineone: <a href="http://fw.hcr2.info">Friendly Wars</a> - <a href="http://tw.hcr2.info">Tractor Wars</a> - <a href="http://vehicles.hcr2.info">Vehicles</a>
linetwo: <a href="http://blog.hcr2.info">Log</a> - <a href="http://tips.hcr2.info">Tips</a> - <a href="http://chests.hcr2.info">Chests</a> - <a href="http://memes.hcr2.info">Memes</a> - <a href="http://gm.hcr2.info">GM</a> - <a href="http://faq.hcr2.info">FAQ</a>
buttonone: <a href="http://hcr2.info">Reference <strong>hcr2.info</strong></a>
buttontwo: <a href="#top">Page <strong>top</strong> </a>
buttonthree: <a href="#bottom">Page <strong>bottom</strong></a>
footerone:  <a href="#bottom"><img src="https://cdn.discordapp.com/attachments/806343355264401478/820076457690398751/GBG-team-logo-125.png" alt="Gas Brake Go"/></a>
footertwo:  <a href="mailto:dadahcr2@gmail.com">dadahcr2@gmail.com</a> ~ dada#1710
